### ISSUE TITLE
Swagger pyang plugin fails if a container doesn't "use" groupings

### ISSUE THREAD

**Issue by grigio60** [ict-strauss/COP#2]
Environment:
Python 3.4.3
Pyang 1.5

The swagger pyang plugin fails with errors when parsing the following (very basic) yang code:

``` yang
module basic {
    namespace "urn:acme:yang:basic";
    prefix "basic";

    container node {
        leaf my-id {
            type uint8;
        }
    }
}
```

This code is valid yang. Pyang validates it without errors and through pyang I'm able to generate the several output formats out of it.... but with swagger plugin, which fails with the following error messages:

> Traceback (most recent call last):
>   File "c:/Python34/Scripts/pyang", line 403, in <module> run()
>   File "c:/Python34/Scripts/pyang", line 377, in run emit_obj.emit(ctx, modules, fd)
>   File "c:\Python34\lib\site-packages\pyang/plugins\swagger.py", line 71, in emit
>      emit_swagger_spec(ctx, modules, fd, ctx.opts.path)
>   File "c:\Python34\lib\site-packages\pyang/plugins\swagger.py", line 139, in emit_swagger_spec
>      gen_apis(chs, path, model['paths'], definitions)
>   File "c:\Python34\lib\site-packages\pyang/plugins\swagger.py", line 316, in gen_apis
>      gen_api_node(child, path, apis, definitions)
>   File "c:\Python34\lib\site-packages\pyang/plugins\swagger.py", line 363, in gen_api_node
>      ref_model[0].arg)
>   IndexError: list index out of range

If I modify the yang code in either of the following ways:

``` yang
module basic {
    namespace "urn:acme:yang:basic";
    prefix "basic";

    grouping node {     //replace "container" with "grouping"
        leaf my-id {
            type uint8;
        }
    }
}
```

or

``` yang
module basic {
    namespace "urn:acme:yang:basic";
    prefix "basic";

    grouping node {     
        leaf my-id {
            type uint8;
        }   
    }

    container myNode {
        uses node;     // the container uses the grouping
    }
}
```

the swagger plugin succeeds in generating the json code.

I have the same failure and error messages from swagger plugins also with these yang definitions:

``` yang
module basic {
    namespace "urn:acme:yang:basic";
    prefix "basic";

    grouping node {     
        leaf my-id {
            type uint8;
        }   
    }

    container anotherNode {
        leaf another-id {
            type uint8; // the container doesn't use the grouping "node"
        }
    }
}
```

and, more interesting, even in this case when a "nested" container doesn't refer to any grouping although the parent container does:

``` yang
module basic {
    namespace "urn:acme:yang:basic";
    prefix "basic";

    grouping node {     
        leaf my-id {
            type uint8;
        }   
    }

    container myNode{
        uses node;                      // the parent container uses the grouping
        container another-node {
            leaf another-id {
                type uint8; // the nested container doesn't use any grouping
            }
        }
    }
}
```

So the conclusion is that the swagger plugin complains if a "container" doesn't include at least one "uses" statement referred to a grouping.

This behaviour is somehow blocking, since yang definitions can't constrain all containers to use mandatorily at least one grouping (it's against RFC6020). Additionaly, the swagger plugin will fail (and it does) when generating json from standard or draft standard yang modules, such as e.g. ietf-alarms.yang which foresees exactly definitions of containers without groupings.

**Comment by arthurMll** [comment]
Hi,
This issue was already fixed in the previous commit. Was due to the previous bug which forced to employ always uses statements inside a "container" or a "list" statement.

**Comment by SapnaDerajeRadhakrishna** [comment]
Hi, I still face the same issue - any idea which commit has this fix?

**Comment by arthurMll** [comment]
Please see answer in [Swagger pyang plugin fails if a container doesn't "use" groupings #303](https://github.com/OpenNetworkingFoundation/EAGLE-Open-Model-Profile-and-Tools/issues/303#issuecomment-413727435)
